# Getting started with TensorFlow

**Learning Objectives**
  1. Practice defining and performing basic operations on constant Tensors


In [2]:
!pip install tensorflow==2.11.0 --user

  Using cached tensorflow-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [3]:
# Ensure the right version of Tensorflow is installed.
!pip freeze | grep tensorflow

tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io==0.34.0
tensorflow-io-gcs-filesystem==0.34.0


In [5]:
import numpy as np

In [4]:
from matplotlib import pyplot as plt

In [5]:
import tensorflow as tf

2023-10-16 02:29:52.738992: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-16 02:29:54.350949: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-10-16 02:29:54.351128: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such 

In [6]:
print(tf.__version__)

2.11.0


## Operations on Tensors

### Variables and Constants

Tensors in TensorFlow are either contant (`tf.constant`) or variables (`tf.Variable`).
Constant values can not be changed, while variables values can be.

In [8]:
x = tf.constant([2, 3, 4])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [9]:
x = tf.Variable(2.0, dtype=tf.float32, name='my_variable')

In [10]:
x.assign(45.8) #1
x

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=45.8>

In [11]:
x.assign_add(4) #2
x

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=49.8>

In [12]:
x.assign_sub(3) #3
x

<tf.Variable 'my_variable:0' shape=() dtype=float32, numpy=46.8>

### Point-wise operations

Tensorflow offers similar point-wise tensor operations as numpy does:
    
* `tf.add` allows to add the components of a tensor 
* `tf.multiply` allows us to multiply the components of a tensor
* `tf.subtract` allow us to substract the components of a tensor
* `tf.math.*` contains the usual math operations to be applied on the components of a tensor
* and many more...

Most of the standard aritmetic operations (`tf.add`, `tf.substrac`, etc.) are overloaded by the usual corresponding arithmetic symbols (`+`, `-`, etc.)

In [13]:
a = tf.constant([5, 3, 8]) #1
b = tf.constant([3, -1, 2])
c = tf.add(a, b)
d = a + b

print("c:", c)
print("d:", d)

c: tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)
d: tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)


In [ ]:
a = tf.constant([5, 3, 8]) #2
b = tf.constant([3, -1, 2])
c = tf.multiply(a, b)
d = a * b

print("c:", c)
print("d:", d)

c: tf.Tensor([15 -3 16], shape=(3,), dtype=int32)
d: tf.Tensor([15 -3 16], shape=(3,), dtype=int32)


In [17]:
# tf.math.exp expects floats so we need to explicitly give the type
a = tf.constant([5, 3, 8], dtype=tf.float32)
b = tf.math.exp(a)

print("b:", b)

b: tf.Tensor([ 148.41316    20.085537 2980.958   ], shape=(3,), dtype=float32)


### NumPy Interoperability

In addition to native TF tensors, tensorflow operations can take native python types and NumPy arrays as operands. 

In [21]:
import numpy as np

In [18]:
# native python list
a_py = [1, 2] 
b_py = [3, 4] 

In [19]:
tf.add(a_py, b_py) #1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [22]:
# numpy arrays
a_np = np.array([1, 2])
b_np = np.array([3, 4])

In [23]:
tf.add(a_np, b_np) #2

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 6])>

In [24]:
# native TF tensor
a_tf = tf.constant([1, 2])
b_tf = tf.constant([3, 4])

In [25]:
tf.add(a_tf, b_tf) #3

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

You can convert a native TF tensor to a NumPy array using .numpy()

In [26]:
a_tf.numpy()

array([1, 2], dtype=int32)